// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mantencion.Data;

namespace mantencion.Migrations
{
    [DbContext(typeof(BaseDatos))]
    [Migration("20210711191800_fix")]
    partial class fix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("mantencion.Data.Mantencion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Mantencions");
                });

            modelBuilder.Entity("mantencion.Data.Material", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombreMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("mantencion.Data.Mecanico", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rut")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Mecanicos");
                });

            modelBuilder.Entity("mantencion.Data.SeUsaEn", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("id_mantencion")
                        .HasColumnType("int");

                    b.Property<int>("id_material")
                        .HasColumnType("int");

                    b.Property<int?>("mantencionid")
                        .HasColumnType("int");

                    b.Property<int?>("materialid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("mantencionid");

                    b.HasIndex("materialid");

                    b.ToTable("SeUsaEns");
                });

            modelBuilder.Entity("mantencion.Data.Trabaja_en", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("horas")
                        .HasColumnType("real");

                    b.Property<int>("id_mantencion")
                        .HasColumnType("int");

                    b.Property<int>("id_mecanico")
                        .HasColumnType("int");

                    b.Property<int?>("mantencionid")
                        .HasColumnType("int");

                    b.Property<int?>("mecanicoid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("mantencionid");

                    b.HasIndex("mecanicoid");

                    b.ToTable("Trabaja_ens");
                });

            modelBuilder.Entity("mantencion.Data.SeUsaEn", b =>
                {
                    b.HasOne("mantencion.Data.Mantencion", "mantencion")
                        .WithMany("SeUsaEns")
                        .HasForeignKey("mantencionid");

                    b.HasOne("mantencion.Data.Material", "material")
                        .WithMany("SeUsaEns")
                        .HasForeignKey("materialid");

                    b.Navigation("mantencion");

                    b.Navigation("material");
                });

            modelBuilder.Entity("mantencion.Data.Trabaja_en", b =>
                {
                    b.HasOne("mantencion.Data.Mantencion", "mantencion")
                        .WithMany("Trabaja_Ens")
                        .HasForeignKey("mantencionid");

                    b.HasOne("mantencion.Data.Mecanico", "mecanico")
                        .WithMany("Trabaja_Ens")
                        .HasForeignKey("mecanicoid");

                    b.Navigation("mantencion");

                    b.Navigation("mecanico");
                });

            modelBuilder.Entity("mantencion.Data.Mantencion", b =>
                {
                    b.Navigation("SeUsaEns");

                    b.Navigation("Trabaja_Ens");
                });

            modelBuilder.Entity("mantencion.Data.Material", b =>
                {
                    b.Navigation("SeUsaEns");
                });

            modelBuilder.Entity("mantencion.Data.Mecanico", b =>
                {
                    b.Navigation("Trabaja_Ens");
                });
#pragma warning restore 612, 618
        }
    }
}
